// Auto-generated by scripts/generate-terminal-content.mjs
// Do not edit manually - run "pnpm generate" to regenerate

import pkg from "../../../../packages/just-bash/package.json";

export const version = pkg.version;

// Command outputs
export const CMD_ABOUT = `just-bash v${pkg.version}
A TypeScript bash interpreter with in-memory filesystem.
Designed for AI agents needing a secure, sandboxed environment.

Custom commands:
  about       About just-bash
  install     Installation instructions
  github      GitHub repository

Or try any bash command: ls, cat, echo, grep, awk, jq, sed, etc.
Type 'help' for a list of all built-in commands.
`;

export const CMD_INSTALL = `npm install just-bash

Usage:
  import { Bash } from "just-bash";
  const bash = new Bash();
  const result = await bash.exec("echo hello");
`;

export const CMD_GITHUB = "https://github.com/vercel-labs/just-bash\n";

// File contents (generated from repo)
export const FILE_README = `# just-bash

A virtual bash environment with an in-memory filesystem, written in TypeScript and designed for AI agents, with broad support for standard Unix commands and bash syntax.

**Note**: This is beta software. Use at your own risk and please provide feedback. See [security model](#security-model).

## Quick Start

\`\`\`bash
npm install just-bash
\`\`\`

\`\`\`typescript
import { Bash } from "just-bash";

const bash = new Bash();
await bash.exec('echo "Hello" > greeting.txt');
const result = await bash.exec("cat greeting.txt");
console.log(result.stdout); // "Hello\\n"
console.log(result.exitCode); // 0
\`\`\`

Each \`exec()\` call gets its own isolated shell state — environment variables, functions, and working directory reset between calls. The **filesystem is shared** across calls, so files written in one \`exec()\` are visible in the next.

## Custom Commands

Extend just-bash with your own TypeScript commands using \`defineCommand\`:

\`\`\`typescript
import { Bash, decodeBytesToUtf8, defineCommand } from "just-bash";

const hello = defineCommand("hello", async (args, ctx) => {
  const name = args[0] || "world";
  return { stdout: \`Hello, \${name}!\\n\`, stderr: "", exitCode: 0 };
});

const upper = defineCommand("upper", async (args, ctx) => {
  // ctx.stdin is a ByteString — decode to text before string ops.
  return {
    stdout: decodeBytesToUtf8(ctx.stdin).toUpperCase(),
    stderr: "",
    exitCode: 0,
  };
});

const bash = new Bash({ customCommands: [hello, upper] });

await bash.exec("hello Alice"); // "Hello, Alice!\\n"
await bash.exec("echo 'test' | upper"); // "TEST\\n"
\`\`\`

Custom command callbacks receive a \`ResolvedCommandContext\` with \`fs\`, \`cwd\`,
\`env\`, \`stdin\`, resolved \`limits\`, and \`exec\` (for subcommands), and work with
pipes, redirections, and all shell features. The legacy \`CommandContext\` remains
available for standalone context inputs; use \`createCommandContext({ fs })\` when
calling a command directly with a fully resolved context.

Host-provided commands preserve the legacy trusted default whether supplied to
the \`Bash\` constructor, declared through \`defineCommand\`, loaded lazily, or
added later with \`bash.registerCommand()\`. Set \`trusted: false\` (or use
\`defineCommand(name, execute, { trusted: false })\`) to select the restricted
extension boundary. Trusted commands run in the embedding process and should
never execute guest-provided JavaScript.

Every invocation is bound by \`maxExecutionTimeMs\`. On cancellation, just-bash
revokes the command context immediately; \`maxExtensionCleanupTimeMs\` only
bounds how long it waits for the now-authority-free command promise to settle.
A late continuation cannot use \`ctx.fs\`, \`ctx.env\`, \`ctx.exec\`, or other context
capabilities. Cleanup work that must run at scope closure can be registered with
\`ctx.executionScope.registerCleanup()\`. A cleanup failure is returned as a
generic exit-126 shell result rather than rejecting \`Bash.exec()\` or exposing
host error details. JavaScript cannot forcibly stop arbitrary host code, so
extensions requiring a hard guarantee against external side effects must run
in a terminable worker or process. Tests that invoke command objects directly
can use \`createCommandContext({ fs })\` to get a fully resolved context without
duplicating internal defaults.

<details>
<summary><h2>Supported Commands</h2></summary>

### File Operations

\`cat\`, \`cp\`, \`file\`, \`ln\`, \`ls\`, \`mkdir\`, \`mv\`, \`readlink\`, \`rm\`, \`rmdir\`, \`split\`, \`stat\`, \`touch\`, \`tree\`

### Text Processing

\`awk\`, \`base64\`, \`column\`, \`comm\`, \`cut\`, \`diff\`, \`expand\`, \`fold\`, \`grep\` (+ \`egrep\`, \`fgrep\`), \`head\`, \`join\`, \`md5sum\`, \`nl\`, \`od\`, \`paste\`, \`printf\`, \`rev\`, \`rg\`, \`sed\`, \`sha1sum\`, \`sha256sum\`, \`sort\`, \`strings\`, \`tac\`, \`tail\`, \`tr\`, \`unexpand\`, \`uniq\`, \`wc\`, \`xargs\`

### Data Processing

\`jq\` (JSON)

### Compression & Archives

\`gzip\` (+ \`gunzip\`, \`zcat\`), \`tar\`

### Navigation & Environment

\`basename\`, \`cd\`, \`dirname\`, \`du\`, \`echo\`, \`env\`, \`export\`, \`find\`, \`hostname\`, \`printenv\`, \`pwd\`, \`tee\`

### Shell Utilities

\`alias\`, \`bash\`, \`chmod\`, \`clear\`, \`date\`, \`expr\`, \`false\`, \`help\`, \`history\`, \`seq\`, \`sh\`, \`sleep\`, \`time\`, \`timeout\`, \`true\`, \`unalias\`, \`which\`, \`whoami\`

All commands support \`--help\` for usage information.

### Shell Features

- **Pipes**: \`cmd1 | cmd2\`
- **Redirections**: \`>\`, \`>>\`, \`2>\`, \`2>&1\`, \`<\`
- **Command chaining**: \`&&\`, \`||\`, \`;\`
- **Variables**: \`$VAR\`, \`\${VAR}\`, \`\${VAR:-default}\`
- **Positional parameters**: \`$1\`, \`$2\`, \`$@\`, \`$#\`
- **Glob patterns**: \`*\`, \`?\`, \`[...]\`
- **If statements**: \`if COND; then CMD; elif COND; then CMD; else CMD; fi\`
- **Functions**: \`function name { ... }\` or \`name() { ... }\`
- **Local variables**: \`local VAR=value\`
- **Loops**: \`for\`, \`while\`, \`until\`
- **Symbolic links**: \`ln -s target link\`
- **Hard links**: \`ln target link\`

</details>

## Configuration

\`\`\`typescript
const env = new Bash({
  files: { "/data/file.txt": "content" }, // Initial files
  env: { MY_VAR: "value" }, // Initial environment
  cwd: "/app", // Starting directory (default: /home/user)
  executionLimits: { maxCallDepth: 50 }, // See "Execution Protection"
});

// Per-exec overrides
await env.exec("echo $TEMP", { env: { TEMP: "value" }, cwd: "/tmp" });

// Pass stdin to the script
await env.exec("cat", { stdin: "hello from stdin\\n" });

// Start with a clean environment
await env.exec("env", { replaceEnv: true, env: { ONLY: "this" } });

// Pass arguments without shell escaping (like spawnSync)
await env.exec("grep", { args: ["-r", "TODO", "src/"] });

// Cancel long-running scripts
const controller = new AbortController();
setTimeout(() => controller.abort(), 5000);
await env.exec("while true; do sleep 1; done", { signal: controller.signal });

// Preserve leading whitespace (e.g., for heredocs)
await env.exec("cat <<EOF\\n  indented\\nEOF", { rawScript: true });
\`\`\`

### Timezone

\`date\` defaults to UTC (\`%Z=UTC\`, \`%z=+0000\`) regardless of the host clock, so the sandbox does not leak the host timezone. To opt into a specific zone, pass \`TZ\` as an initial env var:

\`\`\`typescript
const bash = new Bash({ env: { TZ: "America/New_York" } });
await bash.exec("date"); // Mon Jun  1 09:30:00 EDT 2026
\`\`\`

\`-u\` always forces UTC; an unset or invalid \`$TZ\` falls back to UTC. Setting \`TZ\` exposes that timezone to scripts running in the sandbox, so only pass a value you are comfortable revealing — forwarding the host's real \`$TZ\` (e.g. \`process.env.TZ\`) reintroduces the disclosure that the UTC default exists to prevent.

\`exec()\` options:

| Option | Type | Description |
|---|---|---|
| \`env\` | \`Record<string, string>\` | Environment variables for this execution only |
| \`cwd\` | \`string\` | Working directory for this execution only |
| \`stdin\` | \`string\` | Standard input passed to the script |
| \`args\` | \`string[]\` | Additional argv passed directly to the first command (bypasses shell parsing; does not change \`$1\`, \`$2\`, ...) |
| \`replaceEnv\` | \`boolean\` | Start with empty env instead of merging (default: \`false\`) |
| \`signal\` | \`AbortSignal\` | Cooperative cancellation; stops at next statement boundary |
| \`rawScript\` | \`boolean\` | Skip leading-whitespace normalization (default: \`false\`) |

## Filesystem Options

Four filesystem implementations:

**InMemoryFs** (default) - Pure in-memory filesystem, no disk access:

\`\`\`typescript
import { Bash } from "just-bash";

const env = new Bash({
  files: {
    "/data/config.json": '{"key": "value"}',
    // Lazy: called on first read, cached. Never called if written before read.
    "/data/large.csv": () => "col1,col2\\na,b\\n",
    "/data/remote.txt": async () => (await fetch("https://example.com")).text(),
  },
});
\`\`\`

**OverlayFs** - Copy-on-write over a real directory. Reads come from disk, writes stay in memory:

\`\`\`typescript
import { Bash } from "just-bash";
import { OverlayFs } from "just-bash/fs/overlay-fs";

const overlay = new OverlayFs({
  root: "/path/to/project",
  // Copy-on-write data is bounded independently from real-file reads.
  maxMemoryBytes: 256 * 1024 * 1024,
});
const env = new Bash({ fs: overlay, cwd: overlay.getMountPoint() });

await env.exec("cat package.json"); // reads from disk
await env.exec('echo "modified" > package.json'); // stays in memory
\`\`\`

\`maxMemoryBytes\` defaults to 1 GiB and covers aggregate files retained in the
copy-on-write layer, including append chunks. Set it to the deployment's memory
budget when an \`OverlayFs\` is reused across executions.

**ReadWriteFs** - Direct read-write access to a real directory. Use this if you want the agent to be able to write to your disk:

\`\`\`typescript
import { Bash } from "just-bash";
import { ReadWriteFs } from "just-bash/fs/read-write-fs";

const rwfs = new ReadWriteFs({ root: "/path/to/sandbox" });
const env = new Bash({ fs: rwfs });

await env.exec('echo "hello" > file.txt'); // writes to real filesystem
\`\`\`

Keep \`ReadWriteFs\` pointed at a workspace directory, not at the installed \`just-bash\` package or any other trusted runtime code. Guest-writable roots should stay separate from trusted code.

\`ReadWriteFs\` uses normal in-place filesystem operations for private regular
files. For multiply-linked regular files, it isolates append and metadata
changes by copying the file and replacing only the sandbox directory entry, so
a host-created hard link cannot carry those changes beyond the configured root.
Implicit copies are limited by \`maxCopyOnWriteSize\` (100 MB by default; set it
to \`0\` to disable the limit). Overwrite does not need to copy existing content.
Explicit \`cp\` copies can be limited with the opt-in \`maxCopySize\` option
(unlimited by default). The portable copy path may materialize sparse-file
holes, so embeddings that require a disk-allocation bound should configure
\`maxCopySize\`.

Shared-inode isolation has a few deliberate limitations:

- Append, \`chmod\`, and \`utimes\` on a multiply-linked regular file require read
  access to the file and write access to its parent directory. They fail with
  \`EFBIG\` when the file exceeds \`maxCopyOnWriteSize\`.
- Copies use \`O_NOATIME\` when the Node.js runtime exposes it and retry with
  normal read semantics if the kernel returns \`EPERM\`. Runtimes and platforms
  without \`O_NOATIME\` may update access-time metadata visible through another
  hard link.
- Do not mutate a \`ReadWriteFs\` root concurrently through direct host filesystem
  APIs. Node.js does not expose the descriptor-relative operations needed to
  make pathname validation atomic against an external actor. A concurrent host
  append to a multiply-linked file may be lost when the isolated entry is
  replaced.
- Mutations in overlapping \`ReadWriteFs\` roots are serialized within the
  process. Unrelated roots proceed independently. The queue is not cancellable
  or bounded, so a large mutation can delay later operations in overlapping
  roots even if the requesting script is subsequently aborted.
- Content writes and appends to FIFOs, sockets, devices, and other special files
  are rejected. This avoids indefinitely occupying an overlapping-root mutation
  slot on a blocking special-file open. Metadata operations remain supported
  for single-link special files; multiply-linked special files are rejected
  because they cannot be isolated without changing their file type.
- Private-file and single-link special-file metadata operations use pathname
  APIs to preserve normal host permission semantics. They are not atomic
  against a trusted host actor concurrently replacing that pathname with a
  symlink. With \`allowSymlinks: false\`, symlinks present during normal path
  validation are still rejected.
- Copying a symlink preserves whether its guest target is absolute or relative.
  Only symlinks whose resolved targets remain inside the root are copied.
- Regular-file copies replace the destination entry to prevent writes through
  hard links. Existing destinations must still be writable, and their parent
  directory must be writable so the isolated entry can be committed. Thus a
  writable destination in a non-writable directory cannot be copied over.
  Copying over a FIFO, socket, device, or other special entry is rejected.

**MountableFs** - Mount multiple filesystems at different paths. Combines read-only and read-write filesystems into a unified namespace:

\`\`\`typescript
import { Bash, MountableFs, InMemoryFs } from "just-bash";
import { OverlayFs } from "just-bash/fs/overlay-fs";
import { ReadWriteFs } from "just-bash/fs/read-write-fs";

const fs = new MountableFs({ base: new InMemoryFs() });

// Mount read-only knowledge base
fs.mount("/mnt/knowledge", new OverlayFs({ root: "/path/to/knowledge", readOnly: true }));

// Mount read-write workspace
fs.mount("/home/agent", new ReadWriteFs({ root: "/path/to/workspace" }));

const bash = new Bash({ fs, cwd: "/home/agent" });

await bash.exec("ls /mnt/knowledge"); // reads from knowledge base
await bash.exec("cp /mnt/knowledge/doc.txt ./"); // cross-mount copy
await bash.exec('echo "notes" > notes.txt'); // writes to workspace
\`\`\`

You can also configure mounts in the constructor:

\`\`\`typescript
import { MountableFs, InMemoryFs } from "just-bash";
import { OverlayFs } from "just-bash/fs/overlay-fs";
import { ReadWriteFs } from "just-bash/fs/read-write-fs";

const fs = new MountableFs({
  base: new InMemoryFs(),
  mounts: [
    { mountPoint: "/data", filesystem: new OverlayFs({ root: "/shared/data" }) },
    { mountPoint: "/workspace", filesystem: new ReadWriteFs({ root: "/tmp/work" }) },
  ],
});
\`\`\`

## AST Transform Plugins

Parse bash scripts into an AST, transform them, and serialize back to bash. Good for instrumenting scripts (e.g., capturing per-command stdout/stderr) or extracting metadata before execution.

\`\`\`typescript
import { Bash, BashTransformPipeline, TeePlugin, CommandCollectorPlugin } from "just-bash";

// Standalone pipeline — output can be run by any shell
const pipeline = new BashTransformPipeline()
  .use(new TeePlugin({ outputDir: "/tmp/logs" }))
  .use(new CommandCollectorPlugin());
const result = pipeline.transform("echo hello | grep hello");
result.script;             // transformed bash string
result.metadata.commands;  // ["echo", "grep", "tee"]

// Integrated API — exec() auto-applies transforms and returns metadata
const bash = new Bash();
bash.registerTransformPlugin(new CommandCollectorPlugin());
const execResult = await bash.exec("echo hello | grep hello");
execResult.metadata?.commands; // ["echo", "grep"]
\`\`\`

See [src/transform/README.md](src/transform/README.md) for the full API, built-in plugins, and how to write custom plugins.

## Integrations

### AI SDK Tool

[\`bash-tool\`](https://github.com/vercel-labs/bash-tool) wraps just-bash as an [AI SDK](https://ai-sdk.dev/) tool:

\`\`\`bash
npm install bash-tool
\`\`\`

\`\`\`typescript
import { createBashTool } from "bash-tool";
import { generateText } from "ai";

const bashTool = createBashTool({
  files: { "/data/users.json": '[{"name": "Alice"}, {"name": "Bob"}]' },
});

const result = await generateText({
  model: "anthropic/claude-sonnet-4",
  tools: { bash: bashTool },
  prompt: "Count the users in /data/users.json",
});
\`\`\`

See [bash-tool](https://github.com/vercel-labs/bash-tool) for more.

### Vercel Sandbox Compatible API

\`Sandbox\` is a drop-in replacement for [\`@vercel/sandbox\`](https://vercel.com/docs/vercel-sandbox) — same API, but runs entirely in-process with the virtual filesystem. Start with just-bash for development and testing, swap in a real sandbox when you need a full VM.

\`\`\`typescript
import { Sandbox } from "just-bash";

// Create a sandbox instance
const sandbox = await Sandbox.create({ cwd: "/app" });

// Write files to the virtual filesystem
await sandbox.writeFiles({
  "/app/script.sh": 'echo "Hello World"',
  "/app/data.json": '{"key": "value"}',
});

// Run commands and get results
const cmd = await sandbox.runCommand("bash /app/script.sh");
const output = await cmd.stdout(); // "Hello World\\n"
const exitCode = (await cmd.wait()).exitCode; // 0

// Read files back
const content = await sandbox.readFile("/app/data.json");

// Create directories
await sandbox.mkDir("/app/logs", { recursive: true });

// Clean up (no-op for Bash, but API-compatible)
await sandbox.stop();
\`\`\`

## CLI

### CLI Binary

Install globally (\`npm install -g just-bash\`) for a sandboxed CLI:

\`\`\`bash
# Execute inline script
just-bash -c 'ls -la && cat package.json | head -5'

# Execute with specific project root
just-bash -c 'grep -r "TODO" src/' --root /path/to/project

# Pipe script from stdin
echo 'find . -name "*.ts" | wc -l' | just-bash

# Execute a script file
just-bash ./scripts/deploy.sh

# Get JSON output for programmatic use
just-bash -c 'echo hello' --json
# Output: {"stdout":"hello\\n","stderr":"","exitCode":0}
\`\`\`

The CLI uses OverlayFS — reads come from the real filesystem, but all writes stay in memory and are discarded after execution.

**Important**: The project root is mounted at \`/home/user/project\`. Use this path (or relative paths from the default cwd) to access your files inside the sandbox.

Options:

- \`-c <script>\` - Execute script from argument
- \`--root <path>\` - Root directory (default: current directory)
- \`--cwd <path>\` - Working directory in sandbox
- \`-e, --errexit\` - Exit on first error
- \`--json\` - Output as JSON

### Interactive Shell

\`\`\`bash
pnpm shell
\`\`\`

## Execution Protection

Bash protects against infinite loops and deep recursion with configurable limits:

\`\`\`typescript
const env = new Bash({
  // \`normal\` is the liberal, compatibility-oriented default. Use \`hardened\`
  // for tighter untrusted-workload policy, then override individual resources.
  executionLimitProfile: "hardened",
  executionLimits: {
    maxCallDepth: 100, // Max function recursion depth
    maxCommandCount: 20000, // Shared across nested execution
    maxSourceBytes: 8 * 1024 * 1024, // Shell source before parsing
    maxFileSystemBytes: 256 * 1024 * 1024, // Retained default-FS data
    maxOutputSize: 32 * 1024 * 1024, // Aggregate stdout + stderr bytes
    maxArchiveBytes: 256 * 1024 * 1024, // Expanded archive bytes
    maxExecutionTimeMs: 30_000, // Whole execution wall-clock deadline
    maxExtensionCleanupTimeMs: 25, // Cancellation acknowledgement grace
  },
});
\`\`\`

All resources remain bounded by default in both profiles. Explicit values
override the selected profile; non-negative safe integers and the legacy
\`Infinity\` spelling are accepted. Infinite deadlines omit the corresponding
platform timer rather than overflowing it. Invalid values are rejected when
\`Bash\` is constructed. Error messages identify the resource that was hit.

## Security Model

The Node.js package requires Node \`>=20.19\`.

- The shell only has access to the provided filesystem.
- All execution happens without VM isolation. This does introduce additional risk. The code base was designed to be robust against prototype-pollution attacks and other break outs to the host JS engine and filesystem.
- Execution is protected against infinite loops and deep recursion with configurable limits.
- Host-realm defense-in-depth uses the strongest scoped controls available on
  each supported Node runtime. Where \`node:module.registerHooks()\` is present,
  builtin ESM imports can also be denied only for the untrusted async context;
  older runtimes retain best-effort scoped protection without failing existing
  applications. It never installs a process-global deny-all loader. Query the
  resolved capabilities with \`DefenseInDepthBox.getInstance().getStatus()\`.
  Audit mode reports \`level: "none"\` because it records violations without
  enforcing them.
- Scoped defense uses reversible proxies for \`Reflect\`, \`JSON\`, and \`Math\` and
  restores their host descriptors on deactivation. This is reported as
  \`intrinsicProtection: "scoped-best-effort"\`: same-realm JavaScript that
  cached an intrinsic or a mutation function before activation cannot be fully
  revoked (including the direct \`delete\` operator). The separately named
  \`processLifetimeIntrinsicHardening: true\` option permanently freezes those
  objects and locks selected well-known Symbol descriptors; use it only in a
  disposable or process-lifetime realm. Use an isolated worker/process when
  complete protection and reversible host state are both required.
- Use [Vercel Sandbox](https://vercel.com/docs/vercel-sandbox) if you need a full VM with arbitrary binary execution.

## Browser Support

The core shell, in-memory filesystem, and most built-in commands work in browser environments. \`tar\`, \`gzip\`, \`gunzip\`, \`zcat\`, \`OverlayFs\`, and \`ReadWriteFs\` require Node.js.

## Default Layout

When created without options, Bash provides a Unix-like directory structure:

- \`/home/user\` - Default working directory (and \`$HOME\`)
- \`/bin\` - Contains stubs for all built-in commands
- \`/usr/bin\` - Additional binary directory
- \`/tmp\` - Temporary files directory

Commands can be invoked by path (e.g., \`/bin/ls\`) or by name.

## AI Agent Instructions

For AI agents, [\`bash-tool\`](https://github.com/vercel-labs/bash-tool) provides additional guidance in its \`AGENTS.md\`:

\`\`\`bash
cat node_modules/bash-tool/dist/AGENTS.md
\`\`\`

## License

Apache-2.0
`;

export const FILE_LICENSE = `                                 Apache License
                           Version 2.0, January 2004
                        http://www.apache.org/licenses/

TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION

1.  Definitions.

    "License" shall mean the terms and conditions for use, reproduction,
    and distribution as defined by Sections 1 through 9 of this document.

    "Licensor" shall mean the copyright owner or entity authorized by
    the copyright owner that is granting the License.

    "Legal Entity" shall mean the union of the acting entity and all
    other entities that control, are controlled by, or are under common
    control with that entity. For the purposes of this definition,
    "control" means (i) the power, direct or indirect, to cause the
    direction or management of such entity, whether by contract or
    otherwise, or (ii) ownership of fifty percent (50%) or more of the
    outstanding shares, or (iii) beneficial ownership of such entity.

    "You" (or "Your") shall mean an individual or Legal Entity
    exercising permissions granted by this License.

    "Source" form shall mean the preferred form for making modifications,
    including but not limited to software source code, documentation
    source, and configuration files.

    "Object" form shall mean any form resulting from mechanical
    transformation or translation of a Source form, including but
    not limited to compiled object code, generated documentation,
    and conversions to other media types.

    "Work" shall mean the work of authorship, whether in Source or
    Object form, made available under the License, as indicated by a
    copyright notice that is included in or attached to the work
    (an example is provided in the Appendix below).

    "Derivative Works" shall mean any work, whether in Source or Object
    form, that is based on (or derived from) the Work and for which the
    editorial revisions, annotations, elaborations, or other modifications
    represent, as a whole, an original work of authorship. For the purposes
    of this License, Derivative Works shall not include works that remain
    separable from, or merely link (or bind by name) to the interfaces of,
    the Work and Derivative Works thereof.

    "Contribution" shall mean any work of authorship, including
    the original version of the Work and any modifications or additions
    to that Work or Derivative Works thereof, that is intentionally
    submitted to Licensor for inclusion in the Work by the copyright owner
    or by an individual or Legal Entity authorized to submit on behalf of
    the copyright owner. For the purposes of this definition, "submitted"
    means any form of electronic, verbal, or written communication sent
    to the Licensor or its representatives, including but not limited to
    communication on electronic mailing lists, source code control systems,
    and issue tracking systems that are managed by, or on behalf of, the
    Licensor for the purpose of discussing and improving the Work, but
    excluding communication that is conspicuously marked or otherwise
    designated in writing by the copyright owner as "Not a Contribution."

    "Contributor" shall mean Licensor and any individual or Legal Entity
    on behalf of whom a Contribution has been received by Licensor and
    subsequently incorporated within the Work.

2.  Grant of Copyright License. Subject to the terms and conditions of
    this License, each Contributor hereby grants to You a perpetual,
    worldwide, non-exclusive, no-charge, royalty-free, irrevocable
    copyright license to reproduce, prepare Derivative Works of,
    publicly display, publicly perform, sublicense, and distribute the
    Work and such Derivative Works in Source or Object form.

3.  Grant of Patent License. Subject to the terms and conditions of
    this License, each Contributor hereby grants to You a perpetual,
    worldwide, non-exclusive, no-charge, royalty-free, irrevocable
    (except as stated in this section) patent license to make, have made,
    use, offer to sell, sell, import, and otherwise transfer the Work,
    where such license applies only to those patent claims licensable
    by such Contributor that are necessarily infringed by their
    Contribution(s) alone or by combination of their Contribution(s)
    with the Work to which such Contribution(s) was submitted. If You
    institute patent litigation against any entity (including a
    cross-claim or counterclaim in a lawsuit) alleging that the Work
    or a Contribution incorporated within the Work constitutes direct
    or contributory patent infringement, then any patent licenses
    granted to You under this License for that Work shall terminate
    as of the date such litigation is filed.

4.  Redistribution. You may reproduce and distribute copies of the
    Work or Derivative Works thereof in any medium, with or without
    modifications, and in Source or Object form, provided that You
    meet the following conditions:

    (a) You must give any other recipients of the Work or
    Derivative Works a copy of this License; and

    (b) You must cause any modified files to carry prominent notices
    stating that You changed the files; and

    (c) You must retain, in the Source form of any Derivative Works
    that You distribute, all copyright, patent, trademark, and
    attribution notices from the Source form of the Work,
    excluding those notices that do not pertain to any part of
    the Derivative Works; and

    (d) If the Work includes a "NOTICE" text file as part of its
    distribution, then any Derivative Works that You distribute must
    include a readable copy of the attribution notices contained
    within such NOTICE file, excluding those notices that do not
    pertain to any part of the Derivative Works, in at least one
    of the following places: within a NOTICE text file distributed
    as part of the Derivative Works; within the Source form or
    documentation, if provided along with the Derivative Works; or,
    within a display generated by the Derivative Works, if and
    wherever such third-party notices normally appear. The contents
    of the NOTICE file are for informational purposes only and
    do not modify the License. You may add Your own attribution
    notices within Derivative Works that You distribute, alongside
    or as an addendum to the NOTICE text from the Work, provided
    that such additional attribution notices cannot be construed
    as modifying the License.

    You may add Your own copyright statement to Your modifications and
    may provide additional or different license terms and conditions
    for use, reproduction, or distribution of Your modifications, or
    for any such Derivative Works as a whole, provided Your use,
    reproduction, and distribution of the Work otherwise complies with
    the conditions stated in this License.

5.  Submission of Contributions. Unless You explicitly state otherwise,
    any Contribution intentionally submitted for inclusion in the Work
    by You to the Licensor shall be under the terms and conditions of
    this License, without any additional terms or conditions.
    Notwithstanding the above, nothing herein shall supersede or modify
    the terms of any separate license agreement you may have executed
    with Licensor regarding such Contributions.

6.  Trademarks. This License does not grant permission to use the trade
    names, trademarks, service marks, or product names of the Licensor,
    except as required for reasonable and customary use in describing the
    origin of the Work and reproducing the content of the NOTICE file.

7.  Disclaimer of Warranty. Unless required by applicable law or
    agreed to in writing, Licensor provides the Work (and each
    Contributor provides its Contributions) on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
    implied, including, without limitation, any warranties or conditions
    of TITLE, NON-INFRINGEMENT, MERCHANTABILITY, or FITNESS FOR A
    PARTICULAR PURPOSE. You are solely responsible for determining the
    appropriateness of using or redistributing the Work and assume any
    risks associated with Your exercise of permissions under this License.

8.  Limitation of Liability. In no event and under no legal theory,
    whether in tort (including negligence), contract, or otherwise,
    unless required by applicable law (such as deliberate and grossly
    negligent acts) or agreed to in writing, shall any Contributor be
    liable to You for damages, including any direct, indirect, special,
    incidental, or consequential damages of any character arising as a
    result of this License or out of the use or inability to use the
    Work (including but not limited to damages for loss of goodwill,
    work stoppage, computer failure or malfunction, or any and all
    other commercial damages or losses), even if such Contributor
    has been advised of the possibility of such damages.

9.  Accepting Warranty or Additional Liability. While redistributing
    the Work or Derivative Works thereof, You may choose to offer,
    and charge a fee for, acceptance of support, warranty, indemnity,
    or other liability obligations and/or rights consistent with this
    License. However, in accepting such obligations, You may act only
    on Your own behalf and on Your sole responsibility, not on behalf
    of any other Contributor, and only if You agree to indemnify,
    defend, and hold each Contributor harmless for any liability
    incurred by, or claims asserted against, such Contributor by reason
    of your accepting any such warranty or additional liability.

END OF TERMS AND CONDITIONS

APPENDIX: How to apply the Apache License to your work.

      To apply the Apache License to your work, attach the following
      boilerplate notice, with the fields enclosed by brackets "[]"
      replaced with your own identifying information. (Don't include
      the brackets!)  The text should be enclosed in the appropriate
      comment syntax for the file format. We also recommend that a
      file or class name and description of purpose be included on the
      same "printed page" as the copyright notice for easier
      identification within third-party archives.

Copyright 2025 Vercel Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
`;

export const FILE_PACKAGE_JSON = `{
  "name": "just-bash",
  "version": "3.4.2",
  "description": "A simulated bash environment with virtual filesystem",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/vercel-labs/just-bash.git"
  },
  "homepage": "https://github.com/vercel-labs/just-bash#readme",
  "type": "module",
  "main": "dist/bundle/index.js",
  "types": "dist/index.d.ts",
  "author": "Malte and Claude",
  "license": "Apache-2.0"
}`;

export const FILE_AGENTS_MD = `<!--
This file is distributed as dist/AGENTS.md in the npm package.
It provides instructions for AI agents using just-bash in their projects.
The build process copies this file to dist/AGENTS.md (removing this comment).
TypeScript and bash examples are validated by src/readme.test.ts.
-->

# AGENTS.md - just-bash

Instructions for AI agents using just-bash in projects.

## What is just-bash?

A sandboxed bash interpreter with an in-memory virtual filesystem. Use it when you need to:

- Execute shell commands without real filesystem access
- Run untrusted scripts safely
- Process text with standard Unix tools (grep, sed, awk, jq, etc.)

## For AI Agents

If you're building an AI agent that needs a bash tool, use [\`bash-tool\`](https://github.com/vercel-labs/bash-tool) which is optimized for just-bash:

\`\`\`sh
npm install bash-tool
\`\`\`

\`\`\`typescript
import { createBashTool } from "bash-tool";
import { generateText } from "ai";

const bashTool = createBashTool({
  files: { "/data/users.json": '[{"name": "Alice"}, {"name": "Bob"}]' },
});

const result = await generateText({
  model: "anthropic/claude-sonnet-4",
  tools: { bash: bashTool },
  prompt: "Count the users in /data/users.json",
});
\`\`\`

See the [bash-tool documentation](https://github.com/vercel-labs/bash-tool) for more details.

## Quick Reference

\`\`\`typescript
import { Bash } from "just-bash";

const bash = new Bash({
  files: { "/data/input.txt": "content" }, // Initial files
  cwd: "/data", // Working directory
});

const result = await bash.exec("cat input.txt | grep pattern");
// result.stdout  - command output
// result.stderr  - error output
// result.exitCode - 0 = success, non-zero = failure
\`\`\`

## Key Behaviors

1. **Isolation**: Each \`exec()\` call is isolated. Environment variables, functions, and cwd changes don't persist between calls. Only filesystem changes persist.

2. **No real filesystem**: By default, commands only see the virtual filesystem. Use \`OverlayFs\` to read from a real directory (writes stay in memory).

3. **No binaries/WASM**: Only built-in commands work. You cannot run node, python, or other binaries.

4. **ReadWriteFs root separation**: If you use \`ReadWriteFs\`, point it at a workspace directory, not at the installed \`just-bash\` package or other trusted runtime code.

5. **UTC by default**: \`date\` always shows UTC (\`%Z=UTC\`, \`%z=+0000\`) unless the host opts in by passing \`TZ\` as an env var (e.g. \`new Bash({ env: { TZ: "America/New_York" } })\`). \`-u\` always forces UTC; an invalid \`$TZ\` falls back to UTC.

## Available Commands

**Text processing**: \`awk\`, \`cat\`, \`column\`, \`comm\`, \`cut\`, \`egrep\`, \`expand\`, \`fgrep\`, \`fold\`, \`grep\`, \`head\`, \`join\`, \`nl\`, \`paste\`, \`rev\`, \`rg\`, \`sed\`, \`sort\`, \`strings\`, \`tac\`, \`tail\`, \`tr\`, \`unexpand\`, \`uniq\`, \`wc\`, \`xargs\`

**Data processing**: \`jq\` (JSON)

**File operations**: \`basename\`, \`chmod\`, \`cp\`, \`dirname\`, \`du\`, \`file\`, \`find\`, \`ln\`, \`ls\`, \`mkdir\`, \`mv\`, \`od\`, \`pwd\`, \`readlink\`, \`rm\`, \`rmdir\`, \`split\`, \`stat\`, \`touch\`, \`tree\`

**Utilities**: \`alias\`, \`base64\`, \`bash\`, \`clear\`, \`date\`, \`diff\`, \`echo\`, \`env\`, \`expr\`, \`false\`, \`gzip\`, \`gunzip\`, \`help\`, \`history\`, \`hostname\`, \`md5sum\`, \`printenv\`, \`printf\`, \`seq\`, \`sh\`, \`sha1sum\`, \`sha256sum\`, \`sleep\`, \`tar\`, \`tee\`, \`time\`, \`timeout\`, \`true\`, \`unalias\`, \`which\`, \`whoami\`, \`zcat\`

All commands support \`--help\` for usage details.

## Tools by File Format

### JSON - \`jq\`

\`\`\`bash
# Extract field
jq '.name' data.json

# Filter array
jq '.users[] | select(.active == true)' data.json

# Transform structure
jq '[.items[] | {id, name}]' data.json

# From stdin
echo '{"x":1}' | jq '.x'
\`\`\`

## Common Patterns

### Process JSON with jq

\`\`\`bash
cat data.json | jq '.items[] | select(.active) | .name'
\`\`\`

### Find and process files

\`\`\`bash
find . -name "*.ts" -type f | xargs grep -l "TODO"
\`\`\`

### Text transformation pipeline

\`\`\`bash
cat input.txt | grep -v "^#" | sort | uniq -c | sort -rn | head -10
\`\`\`

### AWK for columnar data

\`\`\`bash
cat data.csv | awk -F',' '{sum += $3} END {print sum}'
\`\`\`

## Limitations

- **32-bit integers only**: Arithmetic operations use 32-bit signed integers
- **No job control**: No \`&\`, \`bg\`, \`fg\`, or process suspension
- **No external binaries**: Only built-in commands are available
- **Execution limits**: Loops, recursion, command counts, and output sizes have configurable limits to prevent runaway execution (exit code 126 when exceeded)

## Error Handling

Always check \`exitCode\`:

\`\`\`typescript
import { Bash } from "just-bash";

const bash = new Bash({ files: { "/file.txt": "some content" } });
const result = await bash.exec("grep pattern file.txt");
if (result.exitCode !== 0) {
  // Command failed - check result.stderr for details
}
\`\`\`

Common exit codes:

- \`0\` - Success
- \`1\` - General error or no matches (grep)
- \`2\` - Misuse of command (invalid options)
- \`126\` - Execution limit exceeded (loops, output size, string length)
- \`127\` - Command not found

## Debugging Tips

1. **Check stderr**: Error messages go to \`result.stderr\`
2. **Use --help**: All commands support \`--help\` for usage
3. **Test incrementally**: Build pipelines step by step
4. **Quote variables**: Use \`"$var"\` to handle spaces in values

## Security Model

- Virtual filesystem is isolated from the real system
- Execution limits prevent infinite loops and resource exhaustion
- No shell injection possible (commands are parsed, not eval'd)

### Execution Limits

All limits are configurable via \`executionLimits\` in \`BashOptions\`:

\`\`\`typescript
const bash = new Bash({
  executionLimits: {
    maxCommandCount: 10000,      // Max commands per exec()
    maxLoopIterations: 10000,    // Max bash loop iterations
    maxCallDepth: 100,           // Max function recursion depth
    maxStringLength: 10485760,   // Max string size (10MB)
    maxArrayElements: 100000,    // Max array elements
    maxGlobOperations: 100000,   // Max glob filesystem operations
    maxAwkIterations: 10000,     // Max AWK loop iterations
    maxSedIterations: 10000,     // Max sed branch loop iterations
    maxJqIterations: 10000,      // Max jq loop iterations
    maxSubstitutionDepth: 50,    // Max $() nesting depth
    maxHeredocSize: 10485760,    // Max heredoc size (10MB)
  },
});
\`\`\`

**Output size limits**: AWK, sed, jq, and printf enforce \`maxStringLength\` on their output buffers. Commands that exceed the limit exit with code 126.

**File read size limits**: \`OverlayFs\` and \`ReadWriteFs\` default to a 10MB max file read size. Override with \`maxFileReadSize\` in filesystem options (set to \`0\` to disable).

## Discovering Types

TypeScript types are available in the \`.d.ts\` files. Use JSDoc-style exploration to understand the API:

\`\`\`bash
# Find all type definition files
find node_modules/just-bash/dist -name "*.d.ts" | head -20

# View main exports and their types
cat node_modules/just-bash/dist/index.d.ts

# View Bash class options
grep -A 30 "interface BashOptions" node_modules/just-bash/dist/Bash.d.ts

# Search for specific types
grep -r "interface.*Options" node_modules/just-bash/dist/*.d.ts
\`\`\`

Key types to explore:
- \`BashOptions\` - Constructor options for \`new Bash()\`
- \`ExecResult\` - Return type of \`bash.exec()\`
- \`InitialFiles\` - File specification format

## Bundling just-bash

just-bash ships pre-bundled (\`dist/bundle/index.js\`, \`index.cjs\`), but a handful
of dependencies are deliberately left **external** — the bundle imports them by
name instead of inlining them. Under plain Node this is invisible: they are
declared dependencies, so the package manager installs them and the imports
resolve at runtime.

It matters when you run just-bash through **another** bundler (Next.js,
webpack, esbuild, rollup) for a serverless or edge target. That bundler will try
to inline these, and some of them cannot be inlined. Mark these three as external:

| Package | What it is |
| --- | --- |
| \`@mongodb-js/zstd\` | native binding (\`optionalDependencies\`) |
| \`node-liblzma\` | native binding (\`optionalDependencies\`) |
| \`seek-bzip\` | CommonJS-only bzip2 decoder |

Next.js 15+:

\`\`\`ts
// next.config.ts
const nextConfig = {
  serverExternalPackages: [
    "just-bash",
    "@mongodb-js/zstd",
    "node-liblzma",
    "seek-bzip",
  ],
};
\`\`\`

Older Next.js uses \`experimental.serverComponentsExternalPackages\`. webpack:
add them to \`externals\` (or use \`webpack-node-externals\`). esbuild/rollup:
\`--external:<name>\` / \`external: [...]\`.

**Node version**: just-bash requires Node \`>=20.19\`.

**Optional dependencies**: \`@mongodb-js/zstd\` and \`node-liblzma\` are declared
in \`optionalDependencies\`, so an install that cannot build them still succeeds.
Only the compression they provide is lost: \`tar -J\` then exits non-zero with
\`xz compression requires node-liblzma which failed to load\`, rather than
crashing the interpreter. \`seek-bzip\` is a regular dependency and is required.
`;

export const FILE_WTF_IS_THIS = `# just-bash website at https://justbash.dev/

This is an interactive demo of **just-bash** running entirely in your browser, with an AI agent that can explore the source code.

The paid-model \`/api/agent\` route is disabled by default in production. Set
\`JUST_BASH_AGENT_API_TOKEN\` and have an authenticated same-origin gateway add
\`Authorization: Bearer <token>\` to enable it. Never embed this server token in
browser JavaScript. The route also bounds request history, output tokens,
agent steps, retries, body-read and execution time, per-instance concurrency,
and admission rate. Production deployments should also add distributed provider/edge
per-principal rate and spend limits; an instance-local counter is not a global
quota in a horizontally scaled deployment.

## Architecture

\`\`\`
+----------------------------------------------------------+
|                        BROWSER                           |
|  +----------+    +----------+    +----------------+      |
|  | xterm.js |--->| just-bash|--->| Virtual FS     |      |
|  | Terminal |    | (browser)|    | (in-memory)    |      |
|  +----------+    +----------+    +----------------+      |
|       |                                                  |
|       | \`agent\` command                                  |
|       v                                                  |
|  +--------------------------------------------------+   |
|  |          SSE Stream (Server-Sent Events)         |   |
|  +--------------------------------------------------+   |
+----------------------------|-----------------------------+
                             |
                             v
+----------------------------------------------------------+
|                        SERVER                            |
|  +-------------+    +----------+    +----------------+   |
|  |ToolLoopAgent|--->| bash-tool|--->| just-bash      |   |
|  | (AI SDK)    |    |          |    | + OverlayFS    |   |
|  |Claude Haiku |    | - bash   |    |                |   |
|  +-------------+    | - read   |    | Real files:    |   |
|                     | - write  |    | - just-bash/   |   |
|                     +----------+    | - bash-tool/   |   |
|                                     +----------------+   |
+----------------------------------------------------------+
\`\`\`

## Components

### 1. just-bash (Browser)
- Pure TypeScript bash interpreter
- Runs locally in browser for regular commands
- In-memory virtual filesystem with pre-loaded files
- No network calls for basic commands like \`ls\`, \`cat\`, \`grep\`

### 2. xterm.js (Browser Terminal)
- Renders a real terminal in the browser
- Handles keyboard input, cursor, colors, scrolling
- Supports ANSI escape codes for styling

### 3. \`agent\` Command
- Custom command that calls the server
- Sends conversation history to \`/api/agent\`
- Streams response via Server-Sent Events (SSE)
- Displays tool calls (bash commands, file reads) in real-time

### 4. ToolLoopAgent (Server - AI SDK)
- Uses Anthropic's Claude Haiku model
- Loops automatically: think -> tool call -> observe -> think -> ...
- Stops after 20 tool calls or when done
- Streams responses back to browser

### 5. bash-tool (Server)
- Provides tools for the AI agent:
  - \`bash\` - Execute bash commands
  - \`readFile\` - Read file contents
  - \`writeFile\` - Write files (disabled in this demo)
- Integrates with just-bash sandbox

### 6. OverlayFS (Server)
- Overlays real filesystem (this source code) as read-only
- Agent can explore just-bash and bash-tool source
- Writes go to memory, not disk

## Data Flow

1. You type \`agent "how does grep work?"\`
2. Browser just-bash runs the \`agent\` command
3. Command POSTs to \`/api/agent\` with message history
4. Server creates ToolLoopAgent with bash-tool
5. Agent thinks, calls tools (bash, readFile), observes results
6. Each step streams back as SSE events
7. Browser displays tool calls and final response
8. Response added to conversation history for multi-turn chat

## Development

\`\`\`bash
pnpm install
pnpm dev
\`\`\`

Open [http://localhost:3000](http://localhost:3000) to see the terminal.

## Links

- **just-bash**: https://github.com/vercel-labs/just-bash
- **bash-tool**: https://github.com/vercel-labs/bash-tool
- **AI SDK**: https://ai-sdk.dev
- **xterm.js**: https://xtermjs.org
`;
